// Generates prisma/seed.sql with PBKDF2-hashed admin password for D1 seeding.
// Usage: npx tsx scripts/generate-seed.ts
// Then: npx wrangler d1 execute shimond-cms --local --file=prisma/seed.sql

import { hashPassword } from '../src/lib/crypto'
import { writeFileSync } from 'fs'

async function main() {
  const adminPassword = await hashPassword('admin123')

  const sql = `-- Seed data for Cloudflare D1
-- Generated by scripts/generate-seed.ts
-- Admin password: admin123 (PBKDF2 hashed)

-- Admin user
INSERT OR IGNORE INTO admin_users (id, username, nickname, password, status, created_at, updated_at)
VALUES ('admin-001', 'admin', '管理员', '${adminPassword}', 'ACTIVE', datetime('now'), datetime('now'));

-- Languages
INSERT OR IGNORE INTO languages (id, code, name, icon, is_rtl, is_active, sort_order, created_at, updated_at)
VALUES
  (lower(hex(randomblob(12))), 'zh', '中文', '🇨🇳', 0, 1, 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'en', 'English', '🇺🇸', 0, 1, 2, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'es', 'Español', '🇪🇸', 0, 1, 3, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'ar', 'العربية', '🇸🇦', 1, 1, 4, datetime('now'), datetime('now'));

-- Default pages
INSERT OR IGNORE INTO pages (id, page_type, name, name_en, slug, status, nav_sort, show_in_nav, created_at, updated_at)
VALUES
  (lower(hex(randomblob(12))), 'home', '首页', 'Home', 'home', 'ACTIVE', 1, 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'about', '关于我们', 'About Us', 'about', 'ACTIVE', 2, 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'products', '产品服务', 'Products', 'products', 'ACTIVE', 3, 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'cases', '案例展示', 'Cases', 'cases', 'ACTIVE', 4, 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'news', '新闻动态', 'News', 'news', 'ACTIVE', 5, 1, datetime('now'), datetime('now')),
  (lower(hex(randomblob(12))), 'contact', '联系我们', 'Contact Us', 'contact', 'ACTIVE', 6, 1, datetime('now'), datetime('now'));

-- Site config
INSERT OR IGNORE INTO site_config (id, company_name, company_name_en, company_name_es, company_name_ar, site_title, site_description, primary_color, secondary_color, accent_color, default_language, phone, email, address, social_links, ai_enabled, created_at, updated_at)
VALUES (
  'default',
  'Shimond',
  'Shimond Industry',
  'Shimond Industria',
  'شيموند',
  'Shimond - Professional PVC Products',
  'Professional manufacturer of high-quality PVC products',
  '#0ea5e9',
  '#f59e0b',
  '#10b981',
  'en',
  '+86 18158194952',
  'service@shimondpvc.com',
  'Building 22, New Material Industrial Park, Wanjiangnan Concentrated area, Chizhou, Anhui, China',
  '{"tiktok":"https://www.tiktok.com/@shimondpvc","facebook":"https://www.facebook.com/shimondpvc","instagram":"https://www.instagram.com/shimondpvc","linkedin":"https://www.linkedin.com/company/shimond","whatsapp":"https://wa.me/8618158194952"}',
  0,
  datetime('now'),
  datetime('now')
);
`

  writeFileSync('prisma/seed.sql', sql, 'utf8')
  console.log('✅ Seed SQL generated at prisma/seed.sql')
}

main().catch((e) => {
  console.error('❌ Failed:', e)
  process.exit(1)
})
